server:
  port: 8081
spring:
  application:
    name: "LoanRequest"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: "mysql"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    root: "INFO"
    com.pragma.bootcamp: "TRACE"
  file:
    name: "logs/backend.log"
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
app:
  base-url: "${AUTH_SERVICE_BASE_URL:http://localhost:8080}"
client:
  user-path: "/api/v1/user/find-document/{dni}"
jwt:
  secret: "VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBmb3Igand0IHNpZ25pbmcgYW5kIGl0IG11c3QgYmUgbG9uZyBlbm91Z2ggdG8gYmUgc2VjdXJl"
  expiration: 3600
adapter:
  sqs:
    region: "sa-east-1"
    queueUrlNotification: "https://sqs.sa-east-1.amazonaws.com/265385633596/loan-notification"
    queueUrlDebtCapacity: "https://sqs.sa-east-1.amazonaws.com/265385633596/debt-capacity"
entrypoint:
  sqs:
    region: "sa-east-1"
    queueUrl: "https://sqs.sa-east-1.amazonaws.com/265385633596/Loan-response"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
