# spring:
#   r2dbc:
#     url: r2dbc:mysql://localhost:3306/pragma
#     username: root
#     password: 12345678
adapters:
  r2dbc:
    host: "localhost"
    port: 3306
    database: "pragma-loan"
    username: "root"
    password: "12345678" # for local dev
#    password: "xyz" # for docker
