adapters:
  r2dbc:
    host: ${ADAPTERS_R2DBC_HOST:localhost}
    port: ${ADAPTERS_R2DBC_PORT:3308}
    database: ${ADAPTERS_R2DBC_DATABASE:loan_db}
    username: ${ADAPTERS_R2DBC_USERNAME:user}
    password: ${ADAPTERS_R2DBC_PASSWORD:password}

