server:
  port: 8081
spring:
  application:
    name: "LoanRequest"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: mysql
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    root: INFO
    com.pragma.bootcamp: TRACE
  file:
    name: logs/backend.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
app:
  base-url: http://localhost:8080
client:
  user-path: /api/v1/user/{dni}
