adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "pragma"
    schema: "public"
    username: "postgres"
    # password: "qwerty" # for local dev
    password: "store" # for docker
